# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname CppFnc
#' @details contiguous: this function checks if g's unique values are
#'   contiguously arranged
#' @export
contiguous <- function(g, error = FALSE) {
    .Call(`_bygrp_contiguous`, g, error)
}

#' @rdname CppFnc
#' @details sum_g: sum numeric values by group
#' @export
sum_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_sum_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details sumi_g: sum integer values by group
#' @export
sumi_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_sumi_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details max_g: calculate the maximum numeric value by group
#' @export
max_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_max_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details maxi_g: calculate the maximum integer value by group
#' @export
maxi_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_maxi_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details min_g: calculate the minimum numeric value by group
#' @export
min_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_min_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details mini_g: calculate the minimum integer value by group
#' @export
mini_g <- function(x, g, na_rm = FALSE, na_opt = FALSE, no_na = FALSE) {
    .Call(`_bygrp_mini_g`, x, g, na_rm, na_opt, no_na)
}

#' @rdname CppFnc
#' @details dup_g: calculate a logical vector indicating duplicated values in x by group
#' @export
dup_g <- function(v, g, na_rm = FALSE) {
    .Call(`_bygrp_dup_g`, v, g, na_rm)
}

#' @rdname CppFnc
#' @details g_id: character grouping as integers
#' @export
g_id <- function(gch) {
    .Call(`_bygrp_g_id`, gch)
}

#' @rdname CppFnc
#' @details g_n: number of observations by group
#' @export
g_n <- function(g) {
    .Call(`_bygrp_g_n`, g)
}

#' @rdname CppFnc
#' @details g_row: row number by group
#' @export
g_row <- function(g) {
    .Call(`_bygrp_g_row`, g)
}

